// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuvpagsucqabvkhqlbwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dnBhZ3N1Y3FhYnZraHFsYndpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTMwMzEsImV4cCI6MjA1NDA4OTAzMX0.xPk-7b1yCluddTQ2bFhWENP1DwAYGdEF5jwIyL5bom8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);